### ISSUE TITLE
7.4.1 crash - `AndroidPlatform.getGoogleAdvertisingInfo`

### ISSUE THREAD

**Issue by matteinn** [Vungle/VungleAds-SDK#29]
Hi there!

Here's the stacktrace for a rare crash experience by production users when using the Android SDK 7.4.1.

Do you know if it has been fixed already in 7.4.2? 
The changelog for the latest version is a bit generic ("Bug fixes and stability improvements") 😄 

Thank you!

```
Caused by java.io.IOException: Google Play services not available
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.zzb(com.google.android.gms:play-services-ads-identifier@@17.1.0:21)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(com.google.android.gms:play-services-ads-identifier@@17.1.0:3)
       at com.vungle.ads.internal.platform.AndroidPlatform.getGoogleAdvertisingInfo(AndroidPlatform.kt:102)
       at com.vungle.ads.internal.platform.AndroidPlatform.getAdvertisingInfo(AndroidPlatform.kt:127)
       at com.vungle.ads.internal.network.VungleApiClient.getDeviceBody$vungle_ads_release(VungleApiClient.kt:652)
       at com.vungle.ads.internal.network.VungleApiClient.getDeviceBody(VungleApiClient.kt:636)
       at com.vungle.ads.internal.network.VungleApiClient.requestBody(VungleApiClient.kt:626)
       at com.vungle.ads.internal.network.VungleApiClient.requestAd(VungleApiClient.kt:339)
       at com.vungle.ads.internal.load.DefaultAdLoader.fetchAdMetadata(DefaultAdLoader.kt:58)
       at com.vungle.ads.internal.load.DefaultAdLoader.requestAd(DefaultAdLoader.kt:43)
       at com.vungle.ads.internal.load.BaseAdLoader.loadAd$lambda-0(BaseAdLoader.kt:203)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.wrapRunnableWithFail(VungleThreadPoolExecutor.kt:36)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion.access$wrapRunnableWithFail(VungleThreadPoolExecutor.kt:31)
       at com.vungle.ads.internal.executor.VungleThreadPoolExecutor$Companion$getWrappedRunnableWithFail$2.run(VungleThreadPoolExecutor.kt:67)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by spielepalast** [comment]
what is the status here?
